using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Domino.Identity;
using Domino.Infrastructure.Api;
using Domino.UI.AppShell;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
static class ContactsTests {
 static int checks;static void Need(bool ok){if(!ok)throw new Exception("Contacts check "+checks);checks++;}
 sealed class Source:IOnboardingShellSource,IContactsSource,ICoachSource {
  public OnboardingStateDto state=new OnboardingStateDto{status="IN_PROGRESS",catalogVersion=2,revision=7,currentStepKey="CONTACTS_STEP",updatedAt="2026-10-01T00:00:00Z",completedStepKeys=Array.Empty<string>(),skippedStepKeys=Array.Empty<string>(),requiredFieldsMissing=Array.Empty<string>(),domainRevisions=new OnboardingDomainRevisionsDto(),answers=new[]{new OnboardingAnswerDto{questionKey="COACH_SELECTION",type="COACH_SELECT",optionKey="MATEO"}}};
  public int prepares,calls,loads;public object first,last;public string error;public bool back,required;public TaskCompletionSource<bool> hold;
  public Task<OnboardingStateDto> LoadAsync(CancellationToken t){loads++;return Task.FromResult(state);}
  public Task<OnboardingCatalogDto> CatalogAsync(string l,CancellationToken t)=>Task.FromResult(new OnboardingCatalogDto{catalogVersion=state.catalogVersion.Value,locale=l,coachCatalogVersion=1,steps=new[]{new OnboardingStepDto{key="CONTACTS_STEP",title=l,required=required,skippable=!required},new OnboardingStepDto{key="MEMBERSHIP_STEP"},new OnboardingStepDto{key="COACH_STEP",questions=new[]{new OnboardingQuestionDto{key="COACH_SELECTION",type="COACH_SELECT"}}}}});
  public object PrepareContactsSkip(){prepares++;return new object();}public object PrepareContactsBack(){back=true;prepares++;return new object();}
  public async Task<OnboardingStateDto> ExecuteContactsAsync(object op,CancellationToken t){calls++;last=op;if(first==null)first=op;if(hold!=null)await hold.Task;if(error=="NETWORK")throw new DominoApiException(ApiFailure.Transport);if(error=="CONFLICT"){state.revision=13;throw new DominoApiException(ApiFailure.Server,409,"REVISION_MISMATCH");}if(error=="VALIDATION")throw new DominoApiException(ApiFailure.Server,400,"ONBOARDING_INVALID_ANSWER");state.revision+=4;state.currentStepKey=back?"COACH_STEP":"MEMBERSHIP_STEP";if(!back)state.skippedStepKeys=new[]{"CONTACTS_STEP"};return state;}
  public Task<CoachCatalogDto> LoadCoachesAsync(string l,int? v,CancellationToken t)=>Task.FromResult(new CoachCatalogDto{catalogVersion=1,resolvedLocale=l,items=new[]{new CoachDto{key="MATEO",name="Mateo",selectable=true}}});
  public object PrepareCoach(string q,string k)=>throw new NotSupportedException();public object PrepareCoachBack()=>throw new NotSupportedException();public Task<OnboardingStateDto> ExecuteCoachAsync(object o,CancellationToken t)=>throw new NotSupportedException();
 }
 sealed class Tokens:IAuthTokenProvider {public Task<string> GetIdTokenAsync(bool refresh,CancellationToken t)=>Task.FromResult("fixture-only");}
 sealed class Wire:IApiTransport {public OnboardingStateDto state;public string first,last,path,method;public bool fail;public Task<ApiHttpResponse> SendAsync(string m,Uri u,string body,string bearer,int timeout,CancellationToken t){if(m=="GET")return Task.FromResult(new ApiHttpResponse(200,JsonConvert.SerializeObject(state)));last=body;first=first??body;path=u.AbsolutePath;method=m;if(fail){fail=false;throw new Exception("isolated transport failure");}state.revision=21;return Task.FromResult(new ApiHttpResponse(200,JsonConvert.SerializeObject(new OnboardingMutationDto{onboarding=state})));}}
 static async Task Main(){
  foreach(int version in new[]{1,2}){var f=new Source();f.state.catalogVersion=version;using(var c=new OnboardingShellController(f)){await c.LoadAsync("en");Need(c.ContactsCanContinue&&c.ContactsCanBack);await c.ChangeContactsLocaleAsync("es");Need(c.Locale=="es"&&c.CurrentStep.title=="es");Need(c.State.revision==7&&c.State.catalogVersion==version&&c.State.currentStepKey=="CONTACTS_STEP");f.error="NETWORK";await c.ContinueContactsAsync();Need(c.ContactsRetry&&c.State.revision==7&&c.State.currentStepKey=="CONTACTS_STEP");Need(!c.ContactsCanBack);await c.ChangeContactsLocaleAsync("en");Need(c.Locale=="es");f.error=null;await c.ContinueContactsAsync();Need(ReferenceEquals(f.first,f.last)&&f.prepares==1);Need(c.State.revision==11&&c.State.currentStepKey=="MEMBERSHIP_STEP"&&c.State.skippedStepKeys.Single()=="CONTACTS_STEP");Need(c.State.answers.Length==1&&c.State.answers[0].questionKey=="COACH_SELECTION");Need(c.ContactsFeedback=="");}}
  var source=new Source();using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.BackContactsAsync();Need(c.State.currentStepKey=="COACH_STEP"&&c.CoachSelection=="MATEO");source.state.currentStepKey="CONTACTS_STEP";source.state.revision=15;await c.LoadAsync("en");Need(c.State.currentStepKey=="CONTACTS_STEP"&&c.State.revision==15&&c.ContactsCanContinue);}
  source=new Source{error="CONFLICT"};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.ContinueContactsAsync();Need(c.State.revision==13&&source.loads==2);Need(source.calls==1&&c.ContactsFeedback=="CONFLICT"&&!c.ContactsRetry);}
  source=new Source{hold=new TaskCompletionSource<bool>()};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");var task=c.ContinueContactsAsync();await c.ContinueContactsAsync();Need(source.calls==1&&c.Busy&&!c.ContactsCanContinue);source.hold.SetResult(true);await task;Need(c.State.revision==11);}
  source=new Source{required=true};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.ContinueContactsAsync();Need(!c.ContactsCanContinue&&source.calls==0);}
  source=new Source{error="VALIDATION"};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.ContinueContactsAsync();Need(c.State.revision==7&&c.ContactsFeedback=="VALIDATION"&&!c.ContactsRetry);}
  var wire=new Wire{state=new Source().state};using(var session=new OnboardingApiSession(new DominoApiConfiguration(true,"https://example.test"),new Tokens(),wire,()=>"fixture-owner",default)){var client=new OnboardingApiClient(session);await client.LoadAsync(default);var adapter=new OnboardingShellApiSource(client);var op=adapter.PrepareContactsSkip();wire.fail=true;try{await adapter.ExecuteContactsAsync(op,default);throw new Exception("Expected failure");}catch(DominoApiException){}await adapter.ExecuteContactsAsync(op,default);var body=JObject.Parse(wire.last);Need(wire.first==wire.last);Need(wire.method=="PUT"&&wire.path.EndsWith("player/onboarding/steps/CONTACTS_STEP"));Need((string)body["action"]=="SKIP"&&((JArray)body["answers"]).Count==0&&((JObject)body["domainRevisions"]).Count==0);Need((int)body["catalogVersion"]==2&&(long)body["expectedRevision"]==7&&!string.IsNullOrEmpty((string)body["operationId"]));Need(client.State.revision==21);}
  Console.WriteLine("CONTACTS_CHECKS="+checks+"_PASS REAL_NETWORK_CALLS=0");
 }
}
