using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Domino.Identity;
using Domino.Infrastructure.Api;
using Domino.UI.AppShell;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
static class MembershipTests {
 static int count;static void Need(bool ok,string name){if(!ok)throw new Exception(name);count++;}
 static MembershipCatalogDto Catalog(string locale)=>JObject.Parse(File.ReadAllText("client/Validation/MembershipCatalogFixture.json"))[locale].ToObject<MembershipCatalogDto>();
 sealed class Source:IOnboardingShellSource,IMembershipSource {
  public OnboardingStateDto state=new OnboardingStateDto{status="IN_PROGRESS",catalogVersion=2,currentStepKey="MEMBERSHIP_STEP",revision=7,updatedAt="2030-01-01T00:00:00Z",answers=Array.Empty<OnboardingAnswerDto>(),domainRevisions=new OnboardingDomainRevisionsDto(),completedStepKeys=Array.Empty<string>(),skippedStepKeys=Array.Empty<string>(),requiredFieldsMissing=Array.Empty<string>()};
  public TrialEligibilityDto eligibility=new TrialEligibilityDto{eligible=true,activationMode="EXPLICIT",policyVersion=3,periodDays=9};
  public EntitlementSummaryDto access=new EntitlementSummaryDto{availability="AVAILABLE",snapshot=new EffectiveEntitlementsDto{plan="FREE",revision=1}};
  public TrialEligibilityDto TrialEligibility=>eligibility;public EntitlementSummaryDto CurrentEntitlements=>access;
  public string error,outcome="ACTIVATED";public bool back,skipFail,skipConflict,dynamic,required;public int trialCalls,trialPrepares,skipCalls,skipPrepares;public object first,last;public TaskCompletionSource<bool> hold;
  public Task<OnboardingStateDto> LoadAsync(CancellationToken token)=>Task.FromResult(state);
  public Task<OnboardingCatalogDto> CatalogAsync(string locale,CancellationToken token)=>Task.FromResult(new OnboardingCatalogDto{catalogVersion=state.catalogVersion.Value,locale=locale,steps=new[]{new OnboardingStepDto{key="MEMBERSHIP_STEP",required=required,skippable=!required},new OnboardingStepDto{key="CONTACTS_STEP"}}});
  public Task<MembershipCatalogDto> LoadMembershipAsync(string locale,int? version,CancellationToken token){var c=Catalog(locale);if(dynamic){c.catalogVersion=12;c.plans[0].active=false;c.plans[1].sortOrder=-100;c.plans=c.plans.Concat(new[]{new MembershipPlanDto{key="FUTURE",name="Future plan",active=true,sortOrder=100,features=Array.Empty<MembershipPlanFeatureDto>()}}).ToArray();}return Task.FromResult(c);}
  public object PrepareMembershipSkip(){skipPrepares++;return new object();}public object PrepareMembershipBack(){back=true;return new object();}
  public Task<OnboardingStateDto> ExecuteMembershipAsync(object operation,CancellationToken token){skipCalls++;if(skipConflict){state.revision=18;state.status="COMPLETED";throw new DominoApiException(ApiFailure.Server,409,"REVISION_MISMATCH");}first=first??operation;last=operation;if(skipFail)throw new DominoApiException(ApiFailure.Transport);state.revision+=5;if(back)state.currentStepKey="CONTACTS_STEP";else state.skippedStepKeys=new[]{"MEMBERSHIP_STEP"};return Task.FromResult(state);}
  public object PrepareTrial(long version){Need(version==3,"authoritative_policy");trialPrepares++;return new object();}
  public async Task<TrialActivationResponseDto> ExecuteTrialAsync(object operation,CancellationToken token){trialCalls++;first=first??operation;last=operation;if(hold!=null)await hold.Task;if(error=="NETWORK")throw new DominoApiException(ApiFailure.Transport);if(error!=null)throw new DominoApiException(ApiFailure.Server,409,error);access=new EntitlementSummaryDto{availability="AVAILABLE",snapshot=new EffectiveEntitlementsDto{plan="PREMIUM_TRIAL",revision=30,trialActive=true,trialEndsAt="2030-01-10T00:00:00Z"}};return new TrialActivationResponseDto{outcome=outcome,entitlements=access};}
 }
 sealed class Tokens:IAuthTokenProvider {public Task<string> GetIdTokenAsync(bool refresh,CancellationToken token)=>Task.FromResult("fixture-only");}
 sealed class Wire:IApiTransport {
  public Source source=new Source();public string first,last,path;public bool fail;public int refreshes;
  public Task<ApiHttpResponse> SendAsync(string method,Uri url,string body,string bearer,int timeout,CancellationToken token){path=url.AbsolutePath;if(method=="GET"){if(path.EndsWith("/entitlements")){refreshes++;return Task.FromResult(new ApiHttpResponse(200,JsonConvert.SerializeObject(source.access)));}return Task.FromResult(new ApiHttpResponse(200,JsonConvert.SerializeObject(source.state)));}first=first??body;last=body;if(fail){fail=false;throw new Exception("fixture transport failure");}if(path.EndsWith("trial/activate")){Need(TrialContractHeader.Required(method,url)&&TrialContractHeader.Value=="1","header_contract");return Task.FromResult(new ApiHttpResponse(200,JsonConvert.SerializeObject(new TrialActivationResponseDto{operationId=(string)JObject.Parse(body)["operationId"],outcome="ALREADY_ACTIVE",entitlements=new EntitlementSummaryDto{availability="AVAILABLE",snapshot=new EffectiveEntitlementsDto{plan="HISTORICAL"}}})));}source.state.revision=20;return Task.FromResult(new ApiHttpResponse(200,JsonConvert.SerializeObject(new OnboardingMutationDto{onboarding=source.state})));}
 }
 static async Task Main(){
  foreach(int version in new[]{1,2}){var f=new Source();f.state.catalogVersion=version;using var c=new OnboardingShellController(f);await c.LoadAsync("en");Need(c.Phase==OnboardingShellPhase.InProgress&&c.Membership.plans.Length==5,"dispatch");var baseline=JsonConvert.SerializeObject(c.MembershipEntitlements);c.SelectMembershipPlan("DIAMOND");c.SelectMembershipPeriod("YEARLY");Need(JsonConvert.SerializeObject(c.MembershipEntitlements)==baseline&&f.trialCalls==0,"preview_no_access");var matrix=JsonConvert.SerializeObject(c.Membership.plans.Select(p=>p.features));c.SelectMembershipPeriod("MONTHLY");Need(matrix==JsonConvert.SerializeObject(c.Membership.plans.Select(p=>p.features)),"period_same_features");await c.ChangeMembershipLocaleAsync("es");Need(c.SelectedMembershipPlan=="DIAMOND"&&c.MembershipBillingPeriod=="MONTHLY"&&c.State.revision==7&&c.State.catalogVersion==version,"locale_preserved");Need(c.Membership.features[0].name=="Análisis de partidas","localized_catalog");c.SelectMembershipPlan("FRIENDS_AND_FAMILY");Need(!c.CanActivateTrial&&c.MembershipIsFamily,"family_no_trial");await c.ActivateMembershipTrialAsync();Need(f.trialCalls==0,"family_no_call");await c.SkipMembershipAsync();Need(f.trialCalls==0&&c.MembershipSkipped&&c.State.revision==12,"skip_server_only");Need(JsonConvert.SerializeObject(c.MembershipEntitlements)==baseline,"skip_access_unchanged");Need(!c.CanSkipMembership,"no_repeat_skip");await c.BackMembershipAsync();Need(c.State.currentStepKey=="CONTACTS_STEP"&&c.State.revision==17,"back_cursor");}
  var source=new Source{eligibility=new TrialEligibilityDto{eligible=false}};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");c.SelectMembershipPlan("FREE");Need(!c.CanActivateTrial,"free_not_eligibility");await c.ActivateMembershipTrialAsync();Need(source.trialCalls==0,"ineligible_no_call");}
  source=new Source{error="NETWORK"};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.ActivateMembershipTrialAsync();Need(c.TrialRetry&&!c.CanSkipMembership&&!c.CanBackMembership,"uncertain_blocks_progress");await c.ChangeMembershipLocaleAsync("es");Need(c.TrialRetry&&c.Locale=="es"&&c.State.revision==7,"pending_locale");source.error=null;await c.ActivateMembershipTrialAsync();Need(ReferenceEquals(source.first,source.last)&&source.trialPrepares==1,"same_trial_operation");Need(c.MembershipEntitlements.snapshot.revision==30&&c.MembershipEntitlements.snapshot.trialEndsAt=="2030-01-10T00:00:00Z","server_access_date");Need(c.State.revision==7&&!c.CanActivateTrial,"trial_not_progress");}
  foreach(string error in new[]{"TRIAL_NOT_ELIGIBLE","TRIAL_ALREADY_CONSUMED","TRIAL_POLICY_VERSION_MISMATCH","TRIAL_DISABLED","IDEMPOTENCY_CONFLICT","CLIENT_UPDATE_REQUIRED","DEPENDENCY_UNAVAILABLE"}){source=new Source{error=error};using var c=new OnboardingShellController(source);await c.LoadAsync("en");await c.ActivateMembershipTrialAsync();Need(c.TrialFeedback==error,"safe_error_"+error);Need(c.MembershipEntitlements.snapshot.plan=="FREE"&&c.State.revision==7,"error_no_access");Need(c.TrialRetry==(error=="DEPENDENCY_UNAVAILABLE"),"retry_classification");}
  source=new Source{hold=new TaskCompletionSource<bool>()};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");var pending=c.ActivateMembershipTrialAsync();await c.ActivateMembershipTrialAsync();await c.SkipMembershipAsync();Need(source.trialCalls==1&&source.skipCalls==0&&c.Busy,"double_submit");source.hold.SetResult(true);await pending;Need(c.TrialFeedback=="ACTIVATED","success");}
  source=new Source{outcome="ALREADY_ACTIVE"};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.ActivateMembershipTrialAsync();Need(c.TrialFeedback=="ALREADY_ACTIVE"&&c.MembershipEntitlements.snapshot.trialEndsAt=="2030-01-10T00:00:00Z","already_active_date");}
  source=new Source{skipFail=true};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.SkipMembershipAsync();source.skipFail=false;await c.SkipMembershipAsync();Need(source.skipPrepares==1&&ReferenceEquals(source.first,source.last),"same_skip_operation");}
  source=new Source{dynamic=true};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");Need(c.Membership.catalogVersion==12&&c.SelectedMembershipPlan=="GOLD","future_order");c.SelectMembershipPlan("FREE");Need(c.SelectedMembershipPlan=="GOLD","inactive");c.SelectMembershipPlan("FUTURE");Need(c.SelectedMembershipPlan=="FUTURE","future_plan");}
  source=new Source{required=true};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.SkipMembershipAsync();Need(source.skipCalls==0,"required_not_skippable");}
  source=new Source{skipConflict=true};using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");await c.SkipMembershipAsync();Need(c.State.revision==18&&c.Phase==OnboardingShellPhase.Completed&&!c.MembershipRetry,"conflict_reloads_authority");Need(source.skipCalls==1&&source.trialCalls==0,"conflict_no_resubmit");}
  source=new Source();using(var c=new OnboardingShellController(source)){await c.LoadAsync("en");c.SelectMembershipPlan("FREE");source.dynamic=true;await c.ChangeMembershipLocaleAsync("es");Need(c.SelectedMembershipPlan=="GOLD"&&c.State.revision==7,"removed_plan_reconciled");}
  var wire=new Wire();using(var session=new OnboardingApiSession(new DominoApiConfiguration(true,"https://example.test"),new Tokens(),wire,()=>"fixture-owner",default)){var api=new OnboardingApiClient(session);await api.LoadAsync(default);var trial=new TrialActivationApiClient(session,null);var adapter=new OnboardingShellApiSource(api,null,null,trial,()=>wire.source.eligibility,()=>wire.source.access);var op=adapter.PrepareTrial(3);wire.fail=true;try{await adapter.ExecuteTrialAsync(op,default);}catch(DominoApiException){}await adapter.ExecuteTrialAsync(op,default);var body=JObject.Parse(wire.last);Need(body.Properties().Select(p=>p.Name).OrderBy(x=>x).SequenceEqual(new[]{"expectedPolicyVersion","operationId"}),"exact_trial_body");Need(wire.first==wire.last&&wire.refreshes==1,"trial_wire_retry_and_refresh");Need(adapter.CurrentEntitlements.snapshot.plan=="FREE","receipt_not_current_access");wire.first=null;await adapter.ExecuteMembershipAsync(adapter.PrepareMembershipSkip(),default);body=JObject.Parse(wire.last);Need(wire.path.EndsWith("/steps/MEMBERSHIP_STEP")&&(string)body["action"]=="SKIP"&&((JArray)body["answers"]).Count==0,"skip_wire");}
  Console.WriteLine("MEMBERSHIP_TESTS="+count+"_PASS REAL_NETWORK_CALLS=0");
 }
}
