using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Domino.Editor;
using Domino.Infrastructure.Api;
using Domino.UI.AppShell;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

static class OnboardingFullFlowTests
{
    static int checks;
    static void Need(bool value,string name){if(!value)throw new Exception(name);checks++;}
    static OnboardingCatalogDto Catalog(int v,string locale)=>new OnboardingCatalogDto{
        catalogVersion=v,locale=locale,requiredCapabilities=Array.Empty<string>(),coachCatalogVersion=1,membershipCatalogVersion=1,
        steps=(v==2?new[]{"BASIC_PROFILE_STEP","EXPERIENCE_STEP","COACH_STEP","CONTACTS_STEP","MEMBERSHIP_STEP"}:new[]{"EXPERIENCE_STEP","COACH_STEP","CONTACTS_STEP","MEMBERSHIP_STEP"}).Select(k=>new OnboardingStepDto{key=k,title=k,required=!k.Contains("CONTACTS")&&!k.Contains("MEMBERSHIP"),skippable=k.Contains("CONTACTS")||k.Contains("MEMBERSHIP"),questions=k=="EXPERIENCE_STEP"?new[]{new OnboardingQuestionDto{key="DOMINO_EXPERIENCE",type="SINGLE_SELECT",options=new[]{"BEGINNER","RULES_KNOWN","STRATEGY","COMPETITIVE"}.Select(x=>new OnboardingOptionDto{key=x,title=x}).ToArray()}}:k=="COACH_STEP"?new[]{new OnboardingQuestionDto{key="COACH_SELECTION",type="COACH_SELECT"}}:Array.Empty<OnboardingQuestionDto>()}).ToArray()};
    static IsolatedOnboardingServer Server(int v=2)=>new IsolatedOnboardingServer(v,Catalog,l=>new CoachCatalogDto{catalogVersion=1,resolvedLocale=l,items=new[]{"MATEO","OMAR"}.Select(k=>new CoachDto{key=k,name=k,selectable=true}).ToArray()},l=>JObject.Parse(File.ReadAllText("client/Validation/MembershipCatalogFixture.json"))[l].ToObject<MembershipCatalogDto>());
    static async Task Profile(OnboardingShellController c,string locale){c.Profile.FirstName="Fixture";c.Profile.LastName="Player";c.Profile.DisplayName="FixturePlayer";c.Profile.Country="CU";await c.ChangeProfileLocaleAsync(locale);await c.SaveProfileAsync();}
    static async Task Resume(IsolatedOnboardingServer s,string locale){using var c=s.Controller(out var session);using(session){int applied=s.Applied,trial=s.TrialApplied;await c.LoadAsync(locale);Need(c.State.currentStepKey==s.State.currentStepKey&&c.State.revision==s.State.revision,"resume_cursor_revision");Need(s.Applied==applied&&s.TrialApplied==trial,"resume_read_only");if(s.State.basicProfile!=null)Need(c.State.basicProfile.displayName==s.State.basicProfile.displayName,"resume_profile");Need(c.State.answers.Length==s.State.answers.Length,"resume_answers");}}
    static async Task Forward(IsolatedOnboardingServer s,OnboardingShellController c,string locale,bool trial=false){
        await c.LoadAsync(locale);Need(c.Phase==OnboardingShellPhase.NotStarted,"initial");await c.StartAsync();Need(c.State.catalogVersion==s.State.catalogVersion&&c.State.revision==14,"start_authority");await Resume(s,locale);
        if(c.State.catalogVersion==2){await Profile(c,locale);if(c.ProfileRetry)await c.SaveProfileAsync();Need(c.State.currentStepKey=="EXPERIENCE_STEP","profile_progress");}
        await Resume(s,locale);c.SelectExperience("STRATEGY");await c.SaveExperienceAsync();if(c.ExperienceRetry)await c.SaveExperienceAsync();Need(c.State.currentStepKey=="COACH_STEP","experience_progress");await Resume(s,locale);
        c.SelectCoach("MATEO");await c.SaveCoachAsync();if(c.CoachRetry)await c.SaveCoachAsync();Need(c.State.currentStepKey=="CONTACTS_STEP","coach_progress");await Resume(s,locale);
        await c.ContinueContactsAsync();if(c.ContactsRetry)await c.ContinueContactsAsync();Need(c.State.currentStepKey=="MEMBERSHIP_STEP","contacts_progress");await Resume(s,locale);
        if(trial){c.SelectMembershipPlan("DIAMOND");await c.ActivateMembershipTrialAsync();Need(c.MembershipEntitlements.snapshot.trialActive&&s.TrialApplied==1,"trial_authority");}
        await c.SkipMembershipAsync();if(c.MembershipRetry)await c.SkipMembershipAsync();Need(c.Phase==OnboardingShellPhase.Completed&&c.State.status==s.State.status,"completed_authority");Need(c.State.revision==s.State.revision,"final_revision");await Resume(s,locale);
        Need(s.Requests.Count(x=>x=="PUT MEMBERSHIP_STEP")>=1&&s.Requests.Count(x=>x=="POST complete")>=1,"separate_complete_endpoint");Need(s.TrialApplied==(trial?1:0),"trial_optional");Need(c.State.answers.GroupBy(a=>a.questionKey).All(g=>g.Count()==1),"no_duplicate_answers");
    }
    static async Task Main(){try{await Run();}catch(Exception e){Console.WriteLine("FAIL="+e.Message);Environment.ExitCode=1;}}
    static async Task Run(){
        foreach(int v in new[]{1,2})foreach(string locale in new[]{"en","es"}){var s=Server(v);using var c=s.Controller(out var session);using(session){await Forward(s,c,locale);Need(s.OperationIds.Distinct().Count()==s.OperationIds.Count,"unique_actions");Need(v==2||!s.Requests.Any(x=>x.Contains("BASIC_PROFILE")),"v1_no_basic");}}
        foreach(string lost in new[]{"BASIC_PROFILE_STEP","EXPERIENCE_STEP","COACH_STEP","CONTACTS_STEP","MEMBERSHIP_STEP","complete"}){var s=Server();s.LoseResponseAt=lost;using var c=s.Controller(out var session);using(session){await Forward(s,c,"en");Need(s.Applied==7,"exactly_once_"+lost);Need(s.OperationIds.Count==8&&s.OperationIds.Distinct().Count()==7,"retry_same_id_"+lost);}}
        {var s=Server();using var c=s.Controller(out var session);using(session){s.LoseResponseAt="start";await c.LoadAsync("en");await c.StartAsync();Need(c.Phase==OnboardingShellPhase.NotStarted&&c.FlowRetry,"start_uncertain");await c.StartAsync();Need(c.Phase==OnboardingShellPhase.InProgress&&s.Applied==1&&s.OperationIds.Distinct().Count()==1,"start_retry");}}
        {var s=Server();using var c=s.Controller(out var session);using(session){await Forward(s,c,"es",true);}}
        // Requiredness belongs to server. No client-side completed flag can bypass it.
        foreach(string missing in new[]{"BASIC_PROFILE_STEP","EXPERIENCE_STEP","COACH_STEP"}){var s=Server();s.State.status="IN_PROGRESS";s.State.catalogVersion=2;s.State.currentStepKey="MEMBERSHIP_STEP";s.State.skippedStepKeys=new[]{"CONTACTS_STEP"};s.State.completedStepKeys=new[]{"BASIC_PROFILE_STEP","EXPERIENCE_STEP","COACH_STEP"}.Where(x=>x!=missing).ToArray();using var c=s.Controller(out var session);using(session){await c.LoadAsync("en");await c.CompleteAsync();Need(c.Phase==OnboardingShellPhase.InProgress&&c.FlowFeedback=="VALIDATION"&&s.Applied==0,"required_"+missing);}}
        {var s=Server();using var c=s.Controller(out var session);using(session){await c.LoadAsync("en");await c.StartAsync();await Profile(c,"es");Need(c.Locale=="es"&&c.Catalog.locale=="es"&&c.State.basicProfile.preferredLocale=="es","locale_switch");c.SelectExperience("STRATEGY");await c.SaveExperienceAsync();c.SelectCoach("MATEO");await c.SaveCoachAsync();await c.ContinueContactsAsync();
            await c.BackMembershipAsync();Need(c.State.currentStepKey=="CONTACTS_STEP","back_contacts");await c.BackContactsAsync();Need(c.CoachSelection=="MATEO","back_coach_prefill");await c.BackCoachAsync();Need(c.ExperienceSelection=="STRATEGY","back_experience_prefill");await c.BackExperienceAsync();Need(c.Profile.DisplayName=="FixturePlayer"&&c.Profile.Language=="es","back_profile_prefill");
            c.Profile.DisplayName="EditedPlayer";await c.SaveProfileAsync();Need(c.State.basicProfile.displayName=="EditedPlayer"&&c.State.currentStepKey=="MEMBERSHIP_STEP","server_first_unresolved");
            await c.BackMembershipAsync();await c.BackContactsAsync();await c.BackCoachAsync();c.SelectExperience("COMPETITIVE");await c.SaveExperienceAsync();Need(c.State.answers.Single(a=>a.questionKey=="DOMINO_EXPERIENCE").optionKey=="COMPETITIVE","edit_experience");
            await c.BackMembershipAsync();await c.BackContactsAsync();c.SelectCoach("OMAR");await c.SaveCoachAsync();Need(c.State.answers.Single(a=>a.questionKey=="COACH_SELECTION").optionKey=="OMAR","edit_coach");await c.SkipMembershipAsync();Need(c.Phase==OnboardingShellPhase.Completed,"edit_complete");}}
        foreach(string error in new[]{"TRIAL_NOT_ELIGIBLE","TRIAL_ALREADY_CONSUMED","TRIAL_POLICY_VERSION_MISMATCH"}){var s=Server();s.State.status="IN_PROGRESS";s.State.catalogVersion=2;s.State.currentStepKey="MEMBERSHIP_STEP";s.State.skippedStepKeys=new[]{"CONTACTS_STEP"};s.State.completedStepKeys=new[]{"BASIC_PROFILE_STEP","EXPERIENCE_STEP","COACH_STEP"};s.TrialError=error;using var c=s.Controller(out var session);using(session){await c.LoadAsync("en");c.SelectMembershipPlan("DIAMOND");string before=JsonConvert.SerializeObject(c.State);await c.ActivateMembershipTrialAsync();Need(JsonConvert.SerializeObject(c.State)==before&&c.CanSkipMembership,"trial_error_intact");await c.SkipMembershipAsync();Need(c.Phase==OnboardingShellPhase.Completed&&s.TrialApplied==0,"trial_error_optional");}}
        {var s=Server();s.State.status="IN_PROGRESS";s.State.catalogVersion=2;s.State.currentStepKey="MEMBERSHIP_STEP";s.State.skippedStepKeys=new[]{"CONTACTS_STEP"};s.State.completedStepKeys=new[]{"BASIC_PROFILE_STEP","EXPERIENCE_STEP","COACH_STEP"};using var c=s.Controller(out var session);using(session){await c.LoadAsync("en");c.SelectMembershipPlan("DIAMOND");s.LoseResponseAt="activate";await c.ActivateMembershipTrialAsync();Need(c.TrialRetry&&!c.CanSkipMembership&&c.State.revision==7,"uncertain_trial_safe");await c.ActivateMembershipTrialAsync();Need(s.TrialApplied==1&&c.CanSkipMembership,"trial_resolved");await c.SkipMembershipAsync();Need(c.Phase==OnboardingShellPhase.Completed,"trial_recovery_complete");}}
        {string owner="fixture-a";var s=Server();using var c=s.Controller(out var session,()=>owner);using(session){await c.LoadAsync("en");s.Hold=new TaskCompletionSource<bool>();var start=c.StartAsync();owner="fixture-b";c.Dispose();var b=Server();using var second=b.Controller(out var sessionB,()=>owner);using(sessionB){await second.LoadAsync("en");s.Hold.SetResult(true);await start;Need(c.State==null&&second.State.status=="NOT_STARTED"&&b.Applied==0,"stale_session_isolation");}}}
        Console.WriteLine("FULL_FLOW_CHECKS="+checks+"_PASS REAL_NETWORK_CALLS=0");
    }
}
