from pathlib import Path
import json,datetime,statistics,re
P=Path('client/Validation/Generated/SERVER7B');run=json.loads((P/'run.json').read_text());result=json.loads((P/'result.json').read_text());rows=json.loads((P/'resources-after.json').read_text());t=lambda x:datetime.datetime.fromisoformat(x['utc']).timestamp();start=datetime.datetime.fromisoformat(run['startedUtc']).timestamp();end=start+result['duration'];b=[x for x in rows if start-65<=t(x)<start];load=[x for x in rows if start<=t(x)<=end];recovery=[json.loads(s) for s in (P/'recovery.jsonl').read_text().splitlines()]
clients=json.loads((P/'client-final-metrics.json').read_text());reg=json.loads((P/'match-registry-final.json').read_text());timeline=[json.loads(s) for s in (P/'timeline.jsonl').read_text().splitlines()]
def cpu(xs,i):return [float(x['containers'][i]['stats']['CPUPerc'].rstrip('%')) for x in xs]
def mem(x,i):
 s=x['containers'][i]['stats']['MemUsage'].split(' /')[0];v,u=re.match(r'([0-9.]+)(\w+)',s).groups();return float(v)*{'B':1,'KiB':1024,'MiB':1024**2,'GiB':1024**3}[u]/1024**2
avg=lambda a:round(statistics.mean(a),2)
D={'SOURCE_SHA':'1d0c3bf3fc5b1aba427b5ab0861372895a7c9e38','RUN_ID':run['runId'],'TARGET_USERS':100,'AUTHENTICATED_USERS':'94_CUMULATIVE_NOT_100_CONCURRENT','PEAK_ACTIVE_WS_SAMPLED':max(x['active'] for x in timeline),'LOAD_GROUPS':5,'CLIENTS_PER_GROUP':20,'RAMP_PATTERN':'0->20->40->60->80; STOP_DURING_GROUP_5', 'GROUP_START_SECONDS':'0.0,22.1,44.9,73.8,105.2'}
for n in (20,40,60,80,100):D['TIME_TO_'+str(n)]=str(round(min((x['elapsed'] for x in timeline if x['active']>=n),default=-1),2))+'s_FIRST_PERIODIC_OBSERVATION' if any(x['active']>=n for x in timeline) else 'NOT_REACHED'
D.update(TIME_TO_100_USERS='NOT_REACHED',STEADY_STATE_DURATION='0_TARGET_NOT_REACHED',TARGET_CONCURRENT_MATCHES=25,MATCHES_STARTED=len(reg['matchIds']),MATCHES_COMPLETED=0,MATCHES_FAILED='NOT_MEASURED_SERVER_FINAL_OUTCOME',MATCHES_ABANDONED='NOT_MEASURED_SERVER_FINAL_OUTCOME',UNASSIGNED_USERS='12_OF_100_TARGET_AT_STOP',BASELINE_API_CPU=str(avg(cpu(b,0)))+'%_DOCKER',AVG_API_CPU=str(avg(cpu(load,0)))+'%_DOCKER',PEAK_API_CPU=str(max(cpu(load,0)))+'%_DOCKER_ANOMALOUS_VS_QUOTA',BASELINE_API_RAM=str(avg([mem(x,0) for x in b]))+' MiB',PEAK_API_RAM=str(max(mem(x,0) for x in load))+' MiB',FINAL_API_RAM=str(mem(recovery[-1],0))+' MiB',BASELINE_REDIS_CPU=str(avg(cpu(b,1)))+'%',PEAK_REDIS_CPU=str(max(cpu(load,1)))+'%',BASELINE_REDIS_RAM=str(avg([mem(x,1) for x in b]))+' MiB',PEAK_REDIS_RAM=str(max(mem(x,1) for x in load))+' MiB',BASELINE_HOST_RAM_AVAILABLE=str(round(statistics.mean(x['hostAvailableBytes'] for x in b)/2**30,3))+' GiB',MIN_HOST_RAM_AVAILABLE=str(round(min(x['hostAvailableBytes'] for x in load)/2**30,3))+' GiB',BASELINE_HOST_LOAD=','.join(str(round(statistics.mean(x['hostLoad'][i] for x in b),2)) for i in range(3)),PEAK_HOST_LOAD=max(x['hostLoad'][0] for x in load),JVM_HEAP_PEAK='NOT_MEASURED',GC_PAUSE='NOT_MEASURED')
for k in 'REST_P50 REST_P95 REST_P99 COMMAND_ACK_P50 COMMAND_ACK_P95 COMMAND_ACK_P99 WS_EVENT_P50 WS_EVENT_P95 WS_EVENT_P99 MATCHMAKING_P50 MATCHMAKING_P95'.split():D[k]='NOT_MEASURED'
for k in 'HTTP_5XX HTTP_429 AUTH_FAILURES WS_CONNECT_FAILURES WS_ABNORMAL_CLOSES RECONNECTS COMMAND_FAILURES'.split():D[k]='0_OBSERVED_CLIENT_LOGS'
D.update(REDIS_ERRORS='0_NEW_ERROR_REPLIES',FIRESTORE_ERRORS='NOT_MEASURED_SERVER_LOGS',UNEXPECTED_EXCEPTIONS='0_OBSERVED_CLIENT_LOGS',OOM_EVENTS=0,REDIS_EVICTIONS=0,REDIS_MEMORY_REJECTIONS='0_OBSERVED_ERRORSTAT_OOM',UNAUTHORIZED_DELIVERIES='NOT_MEASURED',SEQUENCE_REGRESSIONS='NOT_INDEPENDENTLY_VERIFIED',MATCH_CORRUPTIONS='NOT_INDEPENDENTLY_VERIFIED',DUPLICATE_COMMAND_APPLICATIONS='NOT_INDEPENDENTLY_VERIFIED',INVALID_TURN_ACCEPTANCES='NOT_INDEPENDENTLY_VERIFIED',REPLAY_SAMPLE_SIZE=0,REPLAY_SAMPLE_RESULT='NOT_RUN_NO_COMPLETED_MATCHES_OBSERVED',SERVER6_REGRESSION='PASS_5_HISTORY_5_SNAPSHOTS_3_AUTHORIZED_REPLAY_MANIFESTS',REAL_TEST_FIRESTORE_READS='NOT_MEASURED',REAL_TEST_FIRESTORE_WRITES='NOT_MEASURED',REAL_PRODUCTION_FIRESTORE_CALLS=0,ORPHAN_SWARM_PROCESSES=0,POST_LOAD_ACTIVE_WS='0_OWNED_CLIENTS_SERVER_WIDE_NOT_MEASURED',POST_LOAD_REDIS_STATE=str(recovery[-1]['redisKeys'])+'_KEYS_VS_31_BASELINE',POST_LOAD_RESOURCE_LEAKS='NOT_VERIFIED_RESIDUAL_MATCH_STATE',RECOVERY_DURATION=str(round(t(recovery[-1])-t(recovery[0]),1))+'s_OBSERVED',GLOBAL_STOP_REAL_RUN='PASS_API_CPU_THRESHOLD_ALL_5_EXIT_0',SERVER_CONFIGURATION_CHANGED='NO',CLOUDFLARE_CONFIGURATION_CHANGED='NO',DNS_CHANGES=0,COMMIT='NONE',PUSH='NONE',SERVER_7_100_SUCCESS='NO_STOPPED_BEFORE_TARGET',ADVANCE_TO_250='NO_PENDING_REVIEW',NEXT='SERVER-7 100-USER REVIEW')
(P/'final-metrics.json').write_text(json.dumps(D,indent=2));print(json.dumps({k:D[k] for k in ('BASELINE_API_CPU','AVG_API_CPU','PEAK_API_CPU','FINAL_API_RAM','RECOVERY_DURATION')}))
report=Path('client/Validation/SERVER_7_CAPACITY_100_REPORT.md')
base=report.read_text();marker='\n\n## SERVER-7B actual execution — controlled CPU stop\n';base=base.split(marker)[0]
body='''
The earlier identity-preflight STOP above is historical. SERVER-7P subsequently created 100 separate LOAD users; this actual run used only that population. No FHO/functional identity participated in load. The functional account was used only for bounded SERVER-6 preservation reads before and after.

**Result: the 100-user target was not demonstrated.** The predeclared conservative CPU threshold triggered global STOP during group 5. No retry, tuning, replacement match, restart, deployment, commit or push followed. This does not establish the server's maximum capacity.

Before load, API/Redis were healthy with zero restarts/OOM. The fresh baseline covers thirteen samples spanning roughly sixty seconds. The observer runs read-only in the user's root terminal; it collects allowlisted counters, never credentials, key names or log bodies. Container/host data are sampled, not billing telemetry. The collector has a 45-minute automatic lifetime and is not a Swarm process.

Stop thresholds were saved before dispatch: host available memory <1.5 GiB; API container memory >=90%; Docker API CPU >=380% for 30 seconds; metrics older than 25 seconds; any client critical failure, container health/restart/OOM change, Redis eviction or new error reply. The resource observer itself uses Docker stats twice per sample, so sample spacing varied under load. CPU averages below are arithmetic means of observed samples, not continuous integrals.

The VM reports 8 CPUs; API inspection reports NanoCpus=4000000000 and cgroup cpu.max=400000/100000 (four CPUs). Docker nevertheless reported percentages above 400%. Preserve these raw readings but do not equate them with verified CPU consumption or proven four-CPU saturation. CPU instrumentation needs review before selecting another attempt. Global STOP correctly followed the predeclared observed-metric threshold; no post-result threshold was invented.

Five groups launched at 0.0, 22.1, 44.9, 73.8 and 105.2 seconds. The 15-second minimum was extended until the preceding group authenticated. First periodic observations of each connection stage are reported separately; they are not exact handshake timestamps. Ninety-four distinct users authenticated cumulatively, while the highest periodic simultaneous socket observation was 87. Six requested clients did not complete authentication before cancellation. No claim of 94 or 100 simultaneously measured sockets is made.

At the stop decision, 21 matches were registered. Final complete-line reconciliation found one further assignment during shutdown, giving 22 exact match IDs and 88 assigned clients. All IDs are disjoint from the five protected SERVER-6 IDs. No Match 26 or replacement was launched. All five children exited with code 0 after STOP; no forced kill was needed. Their final activeAuthenticatedSockets counts total zero. They submitted 525 normal-cadence commands; no client failure records were observed before the resource stop.

No match completion was observed. Active matches were left to the normal server disconnect lifecycle. Their final server-side abandoned/failed outcomes were not inspected and must not be invented. With no completed sample available, five-match Replay reconstruction was NOT_RUN, not PASS. The GET-only sample downloader was prepared but not invoked. No backend data was deleted or manually rewritten.

SERVER-6 verification found all five history entries and authoritative snapshots both before and after. A first attempt to read the oldest Replay received 403 with the functional account. The bounded check was corrected to respect the three replayAvailable entries advertised by History; all three authorized Replay manifests passed before and after. No entitlement change or authentication bypass occurred. This is bounded preservation evidence, not a repeat reconstruction of all five FHO Replays.

Recovery observed naturally without service restarts. API memory remaining above baseline can reflect retained heap/cache; it is not independently classified as a leak. Redis still has more keys than baseline, with unfinished load matches present at STOP. Per-key ownership/TTL, server-wide WSS, queue/presence/authorization-handle cleanup and JVM workers/heap were not exposed by the available observer. POST_LOAD_RESOURCE_LEAKS therefore remains NOT_VERIFIED. Redis cumulative error replies were already 10 at baseline and did not increase; evictions and observed OOM errors remained zero. Server exception/Firestore operation counters were not collected.

The harness change adds an active-socket gauge and opt-in heartbeat retention for completed clients, without requeue or additional gameplay commands. The intended ten-minute retention never activated because target population was not reached. The Kotlin harness compiled and its existing test suite passed. No production backend was rebuilt/deployed or reconfigured. Earlier pending work is retained; no unrelated file was edited.

Evidence (ignored Generated/SERVER7B): run.json, baseline-resources.json, resources-after.json, timeline.jsonl, client-final-metrics.json, result.json, stop-thresholds.json, server6-before/after.json, recovery.jsonl, match-registry-final.json and separate five group logs. The final registry is authoritative for later reviewed cleanup; the initial registry/result preserve the 21-match stop-time observation. No cleanup is authorized here.

'''
report.write_text(base+marker+body+'```text\n'+'\n'.join(str(k)+'='+str(v) for k,v in D.items())+'\n```\n',encoding='utf-8')
